### PR TITLE
sync latest updates for bootcamp made in internal KP repo

### PR DESCRIPTION
**Pull request by SergeiSizov**

### CODE REVIEW

**Comment by SavvasM1** [comment]
Looks reasonable.

**Comment by SergeiSizov** [comment]
who has rights to approve this?

**Comment by SavvasM1** [comment]
Definitely @chbatey

**Review by SavvasM1 — APPROVED** [review]
Looks reasonable!

**Comment by SergeiSizov** [comment]
@SavvasM1 thanks for approval, but I don't have permission to merge it, so you will have to do it yourself.

**Pull request merged**
